### ISSUE TITLE
More Information

### ISSUE THREAD

**Issue by JohnShortland** [uldiseihenbergs/meshcentral-builds#1]
Can you update the README.MD with some further info such as ports that are used, maybe a compose example or just your docker run example.

**Comment by kameleon25** [comment]
> Can you update the README.MD with some further info such as ports that are used, maybe a compose example or just your docker run example.

I second this. This would be super helpful.

**Comment by uldiseihenbergs** [comment]
Sorry for very late response, i did not received any notification from github.
i'm running this docker in unraid environment, so it just runs with simple run command. and my MC runs behind Apache reverse proxy too.
all config options are in data folder config.json. there are so many options, that i didn't want to start describe it one by one. 
here is my docker run command:
`docker run -d --name='meshcentral2' --net='bridge' -e TZ="Europe/Kiev" -e HOST_OS="Unraid" -p '82:80/tcp' -p '455:8443/tcp' -p '466:443/tcp' -v '/mnt/user/appdata/meshcentral2new/data2/':'/home/node/meshcentral/meshcentral-data':'rw' -v '/mnt/user/backups/meshcentral-files2/':'/home/node/meshcentral/meshcentral-files/':'rw' -v '/mnt/user/appdata/meshcentral2new/web/':'/home/node/meshcentral/meshcentral-web':'rw' -v '/mnt/user/appdata/meshcentral2new/backup':'/home/node/meshcentral/meshcentral-backup':'rw' --hostname=meshcentral.example.com --log-opt max-size=50m --log-opt max-file=1 'uldiseihenbergs/meshcentral:0.5.85' `
