### ISSUE TITLE
Provide image for ARM architecture

### ISSUE THREAD

**Issue by ryansun96** [uldiseihenbergs/meshcentral-builds#4]
Please consider building an ARM64 and / or ARM image

**Comment by uldiseihenbergs** [comment]
huh, i have no single ARM device to test it, so it will be hard to me provide such a support..

**Comment by ryansun96** [comment]
Typically you can use `docker buildx` to build images for a different platform, as long as your current machine supports some emulator (e.g. qemu)(https://docs.docker.com/buildx/working-with-buildx/#build-multi-platform-images). I can build it as a separate image, but ideally we can have yours support multiple architecture

**Comment by uldiseihenbergs** [comment]
this is a bit of my knowledge, but what should i change in my Dockerfile for this? all builds are done by docker hub itself.

**Comment by ryansun96** [comment]
No change to dockerfile is necessary, however after some research *auto* build by docker hub does not support multi-arch yet... If you are interested take a look here and at the bottom you will see a link to use github actions https://github.com/docker/hub-feedback/issues/1874

**Comment by uldiseihenbergs** [comment]
i moved to github actions, at last :)
and i just started to proved images for ARMv7 and ARMx64 too.
please try yourself, as i have no device to test.
Thanks
