### ISSUE TITLE
Issues with some agents connecting on 0.9.28 and 0.9.28d

### ISSUE THREAD

**Issue by githubbiswb** [uldiseihenbergs/meshcentral-builds#6]
Love the container by the way, and I rolled back to the 0.9.9 version and everything is now working as expected except for a few agents I am still troubleshooting. 

I upgraded to 0.9.28d and then rolled back to 0.9.28 although the fingerprint looks the same, and I saw tons of this in my reverse proxy logs

`2021/09/27 09:21:38 [error] 504#504: *8492 connect() failed (111: Connection refused) while connecting to upstream, client: 10.0.0.131, server: meshcentral.*, request: "GET /agent.ashx HTTP/1.1", upstream: "http://192.168.255.141:4430/agent.ashx", host: "meshcentral.biswb.com"
`

Going back to 0.9.9 resolved that error and let most agents connect, but still figured I would pass along the log.

**Comment by githubbiswb** [comment]
ah, that is a good idea. Then I can see if its a mesh problem or this container having issues, I will do that and let you know how it goes

**Comment by githubbiswb** [comment]
That is updated to now 0.9.28 via the self update feature, no error in the logs. No change to the reverse proxy, I am not even bouncing it between mesh container changes. It didn't re-connect the troublesome agents, but I think a reboot on those, and some small troubleshooting will catch those. But the 0.9.28 version without doing the self update seems to still create the error

**Comment by uldiseihenbergs** [comment]
this is really interesting - i created 0.9.28 8 days ago. there is no new version available - how can you update to the same version?

**Comment by uldiseihenbergs** [comment]
and you can this very recent thread about reverse proxy errors: https://github.com/Ylianst/MeshCentral/issues/2831
i'm not sure, if you are affected by this..

**Comment by githubbiswb** [comment]
> 
> 
> and you can this very recent thread about reverse proxy errors: [Ylianst/MeshCentral#2831](https://github.com/Ylianst/MeshCentral/issues/2831)
> i'm not sure, if you are affected by this..

The symptoms are very similar for sure, but what is odd is that is back from Jun, and I haven't had any issues until now. And it only happens when I flip between container versions. But it does seem possible, the error is triggered by something else happening? Very odd for sure

**Comment by githubbiswb** [comment]
So yeah I can't say its for sure something container, I can't say its for sure something mesh on their side, I also don't want to leave this open either for you, you have been super helpful. My plan is to leave things like they are now, and keep doing the self update until the next container you push comes out, and then I will update to it and see how everything is working at that point. Thank you again for the great contaienr and all of your assistance on this particular topic.
